apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: '{{ .Release.Name }}-tls-certificates-provider'
  labels:
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: '{{ .Values.externalSecrets.refreshInterval }}'
  secretStoreRef:
    name: '{{ .Values.externalSecrets.secretStore.name }}'
    kind: SecretStore
  target:
    name: '{{ .Release.Name }}-tls-certificates'
    creationPolicy: Owner
  data:
  - secretKey: 'client-certificate.pem'
    remoteRef:
      key: '{{ .Values.certificates.tls.certificate.key }}'
      property: '{{ .Values.certificates.tls.certificate.property }}'
  - secretKey: 'client-certificate.key'
    remoteRef:
      key: '{{ .Values.certificates.tls.key.key }}'
      property: '{{ .Values.certificates.tls.key.property }}'
  - secretKey: 'client-certificate.ca-bundle'
    remoteRef:
      key: '{{ .Values.certificates.tls.ca.key }}'
      property: '{{ .Values.certificates.tls.ca.property }}'